### ISSUE TITLE
Homepage - Pre footer: Layout is not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#1]
![image](https://cloud.githubusercontent.com/assets/18587097/15884885/7d899fda-2d7d-11e6-9aa9-8baef1de64b2.png)

**Comment by kraisitb** [comment]
This is due to responsive support so we cannot achieve the exact position of the mentioned elements the same way as in the mock.

Note - if you stretch the browser out more, at one point it's actually be positioned very close to how it looks in the mock
