### ISSUE TITLE
Contact Us - Style of form is not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#11]
![image](https://cloud.githubusercontent.com/assets/18587097/15917586/6badf742-2e28-11e6-8951-b2a68f4f2446.png)

**Comment by kraisitb** [comment]
The design was changed / updated during final checking and amendment in order to make the form and button style consistence. Please ignore this one.

**Comment by Atcharanak** [comment]
![image](https://cloud.githubusercontent.com/assets/18587097/16403942/721b1712-3d24-11e6-9c4f-1aa7ce6cbb47.png)
