### ISSUE TITLE
Project Scope - Header:Social Media icons doesn't show in the frontend, once the account's has been created

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#17]
![image](https://cloud.githubusercontent.com/assets/18587097/15921083/1afb76b4-2e49-11e6-806b-4f5f099367a6.png)

**Comment by kraisitb** [comment]
I've discussed this with Mario and we came to an agreement that social links will be implemented later because client is planning to have us creating social media pages for them.

Furthermore, we did not have a design for this section so we just skipped it for now.

**Comment by Atcharanak** [comment]
If refer from design, please update project scope.
Actually, it should ready to show icon once update the url in the backend.

**Comment by kraisitb** [comment]
Scope doc updated, please refer to point PS-1.2.

This is yet to be confirmed so please skip this if possible (we'd need a proper design guide in order to implement this).

**Comment by Atcharanak** [comment]
If there are no url for social media
Just use the url of the log in page for each social media.
Social icons should display then once added at back end.

So please done for this point.

Thank you.

**Comment by kraisitb** [comment]
Social links added in the header.
