### ISSUE TITLE
Homepage - Font size and color is not  correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#2]
H1, H2 color should be #a68e4f
Text content color should be #504b3e and font size should 17px. 
Text lead-in font should be 15px and color should #9f9b9b.
etc.

NOTE: Please check for all page.

**Comment by Atcharanak** [comment]
Size of text content still not 17px

![image](https://cloud.githubusercontent.com/assets/18587097/16403458/98f1b5ee-3d1f-11e6-8737-448b0007219f.png)

**Comment by kraisitb** [comment]
Font size updated.
