### ISSUE TITLE
Project Scope - Homepage(Get In Touch): The all fields is required.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#20]
![image](https://cloud.githubusercontent.com/assets/18587097/15922262/081a3564-2e51-11e6-9a0a-51f22078d80d.png)

**Comment by kraisitb** [comment]
Message textarea is now required for all forms.

Please note that phone number field is not a required field anymore for all forms as per PM request (Pre-live separated task recently assigned)

**Comment by Atcharanak** [comment]
Please update project scope and provide link to the ticket where the change is mentioned.
Thanks.

**Comment by kraisitb** [comment]
https://app.magnetichq.com/Magnetic/OpenPopup.do?popup=ViewTask.do?taskId=78513278&main=Tasks.do
