### ISSUE TITLE
Project Scope - Homepage(Retirement Village's Custom Post): Please create TRUE/FALSE field for the custom post and please limit this to only 3 posts.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#25]
As checked, It's limit on Featured Locations of Homepage.
Could you please confirm? If it's correct, please update project scope.

![image](https://cloud.githubusercontent.com/assets/18587097/15996528/63fd8882-3152-11e6-9777-65e63facacd0.png)

**Comment by kraisitb** [comment]
Limited to 3 as per mock. It was not mentioned in the scope.
