### ISSUE TITLE
Project Scope - About Us(Lead in): This section should be under "Theme Options -> Sidebar tab".

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#27]
As checked, This section is under page.
Could you please confirm? If it's correct, please update project scope.

Note: Also check on other subpage.

![image](https://cloud.githubusercontent.com/assets/18587097/15997081/b556b8f0-3159-11e6-8269-baea18225c73.png)

**Comment by kraisitb** [comment]
I've discussed this with Ev via Skype during development, the sidebar menu should be ACF repeater in each individual page instead of Theme Options because the leadin can be vary across pages.

**Comment by kraisitb** [comment]
Scope doc updated. Same as issue #33 .
