### ISSUE TITLE
Project Scope - Residential Care(Our Locations): This section should from Custom Post: Residential Care.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#28]
As checked, This section is from page.
Could you please confirm? If it's correct, please update project scope.

![image](https://cloud.githubusercontent.com/assets/18587097/15997487/dbe2c3c4-315e-11e6-959b-73728c0e892d.png)

**Comment by kraisitb** [comment]
Link field is limited to 'residential-care' custom post type but other fields are kept as it is allowing user to update each item's title and content freely.

**Comment by Atcharanak** [comment]
as per Project Scope, it should be Custom Post not ACF.

**Comment by kraisitb** [comment]
OK, I've updated the staging and marked this as fixed.

**Comment by Atcharanak** [comment]
Still not fix.
