### ISSUE TITLE
Inner page - Font size and color is not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#3]

**Comment by kraisitb** [comment]
Font size should be correct. I've converted the font size from pt in PSD to px.

For font color there are some changes during development such as button color, anchor link color, etc. So please ignore this if possible.

**Comment by Atcharanak** [comment]
refer: https://github.com/titan-cebu/Meath-Care/issues/2

**Comment by kraisitb** [comment]
Fixed the same way as #2.
