### ISSUE TITLE
Project Scope - Retirement Village(Our Locations): This section should from Custom Post.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#30]
As checked, This section is from page.
Could you please confirm? If it's correct, please update project scope.

![image](https://cloud.githubusercontent.com/assets/18587097/15997745/beb5dfcc-3161-11e6-84d3-de371ab92d48.png)

**Comment by kraisitb** [comment]
Link field is limited to 'retirement-villages' custom post type but other fields are kept as it is allowing user to update each item's title and content freely.

**Comment by Atcharanak** [comment]
Refer comment on https://github.com/titan-cebu/Meath-Care/issues/28
