### ISSUE TITLE
Project Scope - Volunteers(Lead in): Sidebar Menu should be under "Theme Options -> Sidebar tab".

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#33]
As checked, This section is under page.
Could you please confirm? If it's correct, please update project scope.

Note: Also check on Links and Employment Page.

![image](https://cloud.githubusercontent.com/assets/18587097/15998174/48348bdc-3166-11e6-8a74-ef96eec7a2ea.png)

**Comment by kraisitb** [comment]
I've discussed this with Ev via Skype during development, the sidebar menu should be ACF repeater in each individual page instead of Theme Options because the leadin can be vary across pages.

**Comment by Atcharanak** [comment]
So please update project scope.

![image](https://cloud.githubusercontent.com/assets/18587097/16407972/a683a6a6-3d40-11e6-826c-d66aa1b62210.png)

**Comment by kraisitb** [comment]
Scope doc updated.
