### ISSUE TITLE
Footer - Text content should be "Perth Web Design" as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#53]
![image](https://cloud.githubusercontent.com/assets/18587097/16030092/62d7d7ca-3218-11e6-983f-c930cb9bc76b.png)

**Comment by kraisitb** [comment]
Footer text updated to "Perth Web Design by Titan Web.".

The "by Titan Web" part is part of Titan theme core function so I didn't change it.
