### ISSUE TITLE
Page content - Vision & Mission Page: Style of text content is no same with web copy. (should not bullet all of list)

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#59]
![image](https://cloud.githubusercontent.com/assets/18587097/16032343/fcd93506-322e-11e6-89f9-c0e83788855a.png)

**Comment by kraisitb** [comment]
Content is managed by PM. Please ignore this issue.

Project end date: May 13th
Page latest revision: June 16th
