### ISSUE TITLE
Page Content - Residential Care Single Page(Kingsley):There is no Download the Kingsley Brochure link in web copy.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#61]
Is it correct?
Please confirm.

![image](https://cloud.githubusercontent.com/assets/18587097/16033138/8a75a0ca-3234-11e6-8a4a-9b14e359dc60.png)

**Comment by kraisitb** [comment]
Correct. The button is added as per PM request.
