### ISSUE TITLE
Residential Care Single Page - The size of image is not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#7]
NOTE: Please also update on Retirement Village Single Page.

![image](https://cloud.githubusercontent.com/assets/18587097/15915994/5d7c52be-2e18-11e6-927a-2da91a0e2740.png)

**Comment by kraisitb** [comment]
Using percentage for width of image elements for responsive purpose. But fit 100% in bootstrap grid.
