### ISSUE TITLE
Residential Care Single Page - Text of address details is not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Meath-Care#8]
NOTE: Please also update on Retirement Village Single Page.

![image](https://cloud.githubusercontent.com/assets/18587097/15916601/c37e6934-2e1e-11e6-90a6-b16de84c470d.png)

**Comment by Atcharanak** [comment]
Please update project scope.

**Comment by kraisitb** [comment]
Scope doc updated, please refer to comment section of point PS-11.0 / PS-13.0.
